# Generated by Django 5.0.2 on 2024-04-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_poll_userpollanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='third_and',
            new_name='third_ans',
        ),
    ]
