# Generated by Django 5.0.2 on 2024-04-29 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_test_usertestanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestanswer',
            name='poll',
        ),
        migrations.AddField(
            model_name='usertestanswer',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.test'),
        ),
    ]
