# Generated by Django 5.0.2 on 2024-05-20 11:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloserUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=70)),
                ('second_name', models.CharField(blank=True, max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(null=True)),
                ('current_city', models.CharField(blank=True, max_length=85)),
                ('current_state', models.CharField(blank=True, max_length=85)),
                ('current_country', models.CharField(blank=True, max_length=28)),
                ('home_city', models.CharField(blank=True, max_length=85)),
                ('home_state', models.CharField(blank=True, max_length=85)),
                ('home_country', models.CharField(blank=True, max_length=28)),
                ('profile_picture_url', models.ImageField(blank=True, upload_to='profile_picture/')),
                ('background_picture_url', models.ImageField(blank=True, upload_to='background_picture/')),
                ('about_me', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, choices=[('Unspecified', 'Unspecified'), ('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Shinto', 'Shinto'), ('Taoism', 'Taoism'), ('Voodoo', 'Voodoo'), ('Folk religion', 'Folk religion'), ('Atheism', 'Atheism')], max_length=20)),
                ('relationship', models.CharField(blank=True, choices=[('Unspecified', 'Unspecified'), ('Single', 'Single'), ('Married', 'Married'), ('Engaged', 'Engaged'), ('Complicated', 'Complicated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Polyamorous', 'Polyamorous'), ('FWB', 'FWB')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Unspecified', 'Unspecified'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Helikopter szturmowy', 'Helikopter szturmowy')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], max_length=8)),
                ('accepting_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('inviting_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
