# Generated by Django 5.0.2 on 2024-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloserUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=70)),
                ('second_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('current_city', models.CharField(max_length=85)),
                ('current_state', models.CharField(max_length=85)),
                ('current_country', models.CharField(max_length=28)),
                ('home_city', models.CharField(max_length=85)),
                ('home_state', models.CharField(max_length=85)),
                ('home_country', models.CharField(max_length=28)),
                ('profile_picutre_url', models.CharField(max_length=100)),
                ('background_picture_url', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=150)),
                ('education', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
