# Generated by Django 5.0.2 on 2024-03-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_closeruser_is_active_closeruser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeruser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
