# Generated by Django 5.0.2 on 2024-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_closeruser_options_alter_closeruser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeruser',
            name='background_picture_url',
            field=models.ImageField(upload_to='files/background_picture'),
        ),
        migrations.AlterField(
            model_name='closeruser',
            name='profile_picutre_url',
            field=models.ImageField(upload_to='files/profile_picture'),
        ),
    ]
