# Generated by Django 5.0.2 on 2024-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_closeruser_background_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeruser',
            name='background_picture_url',
            field=models.ImageField(upload_to='background_picture/'),
        ),
        migrations.AlterField(
            model_name='closeruser',
            name='profile_picutre_url',
            field=models.ImageField(upload_to='profile_picture/'),
        ),
    ]
