# Generated by Django 5.0.2 on 2024-03-17 18:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_closeruser_background_picture_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closeruser',
            old_name='profile_picutre_url',
            new_name='profile_picture_url',
        ),
        migrations.AlterField(
            model_name='closeruser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
