# Generated by Django 5.0.2 on 2024-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_profile_picutre_url_closeruser_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeruser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
