# Generated by Django 5.0.2 on 2024-03-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_closeruser_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeruser',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
