# Generated by Django 5.0.2 on 2024-05-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='badge',
        ),
        migrations.AddField(
            model_name='badges',
            name='new_user_badge',
            field=models.CharField(choices=[('1', 'Newuser'), ('2', 'Poster'), ('3', 'Shorter'), ('4', 'Poller'), ('5', 'Tester')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='badges',
            name='poller_badge',
            field=models.CharField(choices=[('1', 'Newuser'), ('2', 'Poster'), ('3', 'Shorter'), ('4', 'Poller'), ('5', 'Tester')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='badges',
            name='poster_badge',
            field=models.CharField(choices=[('1', 'Newuser'), ('2', 'Poster'), ('3', 'Shorter'), ('4', 'Poller'), ('5', 'Tester')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='badges',
            name='shorter_badge',
            field=models.CharField(choices=[('1', 'Newuser'), ('2', 'Poster'), ('3', 'Shorter'), ('4', 'Poller'), ('5', 'Tester')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='badges',
            name='tester_badge',
            field=models.CharField(choices=[('1', 'Newuser'), ('2', 'Poster'), ('3', 'Shorter'), ('4', 'Poller'), ('5', 'Tester')], default='', max_length=20),
        ),
    ]
